INSERT INTO candidate(first_name, last_name) VALUES ('Herman', 'Elu');
INSERT INTO candidate(first_name, last_name) VALUES ('Tormi', 'Sulnis');
INSERT INTO candidate(first_name, last_name) VALUES ('Lotte', 'Endel');
INSERT INTO candidate(first_name, last_name) VALUES ('Leevike', 'Kasetohi');
INSERT INTO candidate(first_name, last_name) VALUES ('Vootele', 'Suss');
INSERT INTO interview(first_name, last_name, interview_type, interview_time) VALUES ('Heli', 'Kopter', 'INFORMAL', '2023-04-19T10:30:30');
INSERT INTO interview(first_name, last_name, interview_type, interview_time) VALUES ('Koduke', 'Setlinna', 'FINAL', '2023-05-05T13:00:00');
INSERT INTO interview(first_name, last_name, interview_type, interview_time) VALUES ('Ahsa', 'Mait', 'TECHNICAL', '2023-06-03T14:15:00');
INSERT INTO application(application_state, updated_on, candidate_id, interview_id) VALUES('INTERVIEW', CURRENT_TIMESTAMP, 1, 1);
INSERT INTO application(application_state, updated_on, candidate_id) VALUES('NEW', CURRENT_TIMESTAMP, 2);
INSERT INTO application(application_state, updated_on, candidate_id) VALUES('NEW', CURRENT_TIMESTAMP, 3);
INSERT INTO application(application_state, updated_on, candidate_id, interview_id) VALUES('INTERVIEW', CURRENT_TIMESTAMP, 4, 2);
INSERT INTO application(application_state, updated_on, candidate_id, interview_id) VALUES('INTERVIEW', CURRENT_TIMESTAMP, 5, 3);
INSERT INTO application(application_state, updated_on, candidate_id) VALUES('NEW', CURRENT_TIMESTAMP, 5);
