INSERT INTO candidate(id, first_name, last_name) VALUES (1, 'Herman', 'Elu');
INSERT INTO candidate(id, first_name, last_name) VALUES (2, 'Tormi', 'Sulnis');
INSERT INTO candidate(id, first_name, last_name) VALUES (3, 'Lotte', 'Endel');
INSERT INTO candidate(id, first_name, last_name) VALUES (4, 'Leevike', 'Kasetohi');
INSERT INTO candidate(id, first_name, last_name) VALUES (5, 'Vootele', 'Suss');
INSERT INTO interview(id, first_name, last_name, interview_type, interview_time) VALUES (1, 'Heli', 'Kopter', 'INFORMAL', '2023-04-19T10:30:30');
INSERT INTO interview(id, first_name, last_name, interview_type, interview_time) VALUES (2, 'Koduke', 'Setlinna', 'FINAL', '2023-05-05T13:00:00');
INSERT INTO interview(id, first_name, last_name, interview_type, interview_time) VALUES (3, 'Ahsa', 'Mait', 'TECHNICAL', '2023-06-03T14:15:00');
INSERT INTO application(id, application_state, updated_on, candidate_id, interview_id) VALUES(1, 'INTERVIEW', CURRENT_TIMESTAMP, 1, 1);
INSERT INTO application(id, application_state, updated_on, candidate_id) VALUES(2, 'NEW', CURRENT_TIMESTAMP, 2);
INSERT INTO application(id, application_state, updated_on, candidate_id) VALUES(3, 'NEW', CURRENT_TIMESTAMP, 3);
INSERT INTO application(id, application_state, updated_on, candidate_id, interview_id) VALUES(4, 'INTERVIEW', CURRENT_TIMESTAMP, 4, 2);
INSERT INTO application(id, application_state, updated_on, candidate_id, interview_id) VALUES(5, 'INTERVIEW', CURRENT_TIMESTAMP, 5, 3);
INSERT INTO application(id, application_state, updated_on, candidate_id) VALUES(6, 'NEW', CURRENT_TIMESTAMP, 5);